### ISSUE TITLE
Experimental splice on scalar is now forbidden

### ISSUE THREAD

**Issue by eserte** [odyniec/p5-Test-Mock-HTTP-Tiny#1]
With perl 5.23.x this construct is now forbidden. See http://www.cpantesters.org/cpan/report/ede6e09e-5a2e-11e5-b125-dd0fe1bfc7aa for a sample fail report and http://matrix.cpantesters.org/?dist=Test-Mock-HTTP-Tiny%200.001 for a fail/pass overview.

**Comment by odyniec** [comment]
Fixed in v0.002. Thanks!
